PRODUCT_PACKAGES += \
	IconPackCircularAndroidOverlay \
	IconPackCircularLauncherOverlay \
	IconPackCircularSettingsOverlay \
	IconPackCircularSystemUIOverlay \
	IconPackCircularThemePickerOverlay \
        IconPackPUIAndroidOverlay \
        IconPackPUILauncherOverlay \
        IconPackPUISystemUIOverlay \
        IconPackPUIThemePickerOverlay \
	IconPackVictorAndroidOverlay \
	IconPackVictorLauncherOverlay \
	IconPackVictorSettingsOverlay \
	IconPackVictorSystemUIOverlay \
	IconPackVictorThemePickerOverlay \
	IconPackSamAndroidOverlay \
	IconPackSamLauncherOverlay \
	IconPackSamSettingsOverlay \
	IconPackSamSystemUIOverlay \
	IconPackSamThemePickerOverlay \
	IconPackKaiAndroidOverlay \
	IconPackKaiLauncherOverlay \
	IconPackKaiSettingsOverlay \
	IconPackKaiSystemUIOverlay \
	IconPackKaiThemePickerOverlay \
	IconPackFilledAndroidOverlay \
	IconPackFilledLauncherOverlay \
	IconPackFilledSettingsOverlay \
	IconPackFilledSystemUIOverlay \
	IconPackFilledThemePickerOverlay \
	IconPackRoundedAndroidOverlay \
	IconPackRoundedLauncherOverlay \
	IconPackRoundedSettingsOverlay \
	IconPackRoundedSystemUIOverlay \
	IconPackRoundedThemePickerOverlay \
	IconPackAcherusAndroidOverlay \
        IconPackAcherusSettingsOverlay \
	IconPackAcherusSystemUIOverlay \
        IconPackOutlineAndroidOverlay \
        IconPackOutlineSettingsOverlay \
        IconPackOutlineSystemUIOverlay \
        IconPackDoraAndroidOverlay \
        IconPackDoraSettingsOverlay \
        IconPackDoraSystemUIOverlay

