PRODUCT_PACKAGES += \
	IconPackCircularAndroidOverlay \
	IconPackCircularLauncherOverlay \
	IconPackCircularSettingsOverlay \
	IconPackCircularSystemUIOverlay \
	IconPackCircularThemePickerOverlay \
	IconPackVictorAndroidOverlay \
	IconPackVictorLauncherOverlay \
	IconPackVictorSettingsOverlay \
	IconPackVictorSystemUIOverlay \
	IconPackVictorThemePickerOverlay \
	IconPackSamAndroidOverlay \
	IconPackSamLauncherOverlay \
	IconPackSamSettingsOverlay \
	IconPackSamSystemUIOverlay \
	IconPackSamThemePickerOverlay \
	IconPackKaiAndroidOverlay \
	IconPackKaiLauncherOverlay \
	IconPackKaiSettingsOverlay \
	IconPackKaiSystemUIOverlay \
	IconPackKaiThemePickerOverlay \
	IconPackFilledAndroidOverlay \
	IconPackFilledLauncherOverlay \
	IconPackFilledSettingsOverlay \
	IconPackFilledSystemUIOverlay \
	IconPackFilledThemePickerOverlay \
	IconPackRoundedAndroidOverlay \
	IconPackRoundedLauncherOverlay \
	IconPackRoundedSettingsOverlay \
	IconPackRoundedSystemUIOverlay \
	IconPackRoundedThemePickerOverlay \
	IconPackOOSAndroidOverlay \
	IconPackOOSSystemUIOverlay \
	IconPackAcherusAndroidOverlay \
	IconPackAcherusSystemUIOverlay